<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionalesI/blob/main/Semana9/SLDescenso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time

In [21]:
def Plotter(e):

  fig = plt.figure(figsize=(6,3))
  ax = fig.add_subplot(121)
  ax1 = fig.add_subplot(122)

  ax.set_title('Epoch: {:.0f}'.format(e),fontsize=10)

  return fig,ax,ax1

In [22]:
G1=(lambda x,y,z: 3*x - y - z - 1., \
    lambda x,y,z: -x + 3*y + z - 3., \
    lambda x,y,z: 2*x + y + 4*z - 7.)

In [23]:
def GetF(G,r):

  n = r.shape[0]
  v = np.zeros(n)

  for i in range(n):
    v[i] = G[i](r[0],r[1],r[2])

  return v

In [24]:
GetF(G1,np.array([0,1,1]))

array([-3.,  1., -2.])

In [25]:
def Metric(G,r):
  return 0.5*np.linalg.norm(GetF(G,r))**2

In [26]:
Metric(G1,np.array([1,1,1]))

0.0

In [29]:
def GetJacobian(f,r,h=1e-3):

  n = r.shape[0]

  J = np.zeros((n,n))

  for i in range(n):
    for j in range(n):

      rf = r.copy()
      rb = r.copy()

      rf[j] = rf[j] + h
      rb[j] = rb[j] - h

      J[i,j] = (f[i](rf[0],rf[1],rf[2]) - f[i](rb[0],rb[1],rb[2]))/(2*h)

  return J

In [31]:
GetJacobian(G1,np.array([1.,3.,4.]))

array([[ 3., -1., -1.],
       [-1.,  3.,  1.],
       [ 2.,  1.,  4.]])

In [42]:
def Minimizer(G,r,lr=1e-4,epochs=int(1e3),error=1e-4):

  metric = 1
  it = 0

  M = np.array([])
  R = np.array([r])

  while metric > error and it < epochs:

    M = np.append(M,Metric(G,r))

    J = GetJacobian(G,r).T
    Vector = GetF(G,r)

    r = r - lr*np.dot(J,Vector)

    R = np.vstack((R,r))

    metric = Metric(G,r)

    if it%2 == 0:
      clear_output(wait=True)
      _,ax,ax1 = Plotter(it)

      ax.plot(R[:it])
      ax1.plot(M[:it],color='r')

      plt.show()

      time.sleep(0.02)




    it += 1

  return r,it

In [43]:
xsol, it = Minimizer(G1,np.array([0,0,0]))

KeyboardInterrupt: 

In [37]:
xsol

array([0.00125908, 0.00134874, 0.00269742])