<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionalesI/blob/main/Semana12/TeoremaBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
Prior = np.array([0.5,0.25,0.25])

In [4]:
Likelihood = np.array([0.9,0.6,0.2])

In [5]:
Total = np.sum(Prior*Likelihood)
Total

0.65

In [6]:
Posterior = Prior*Likelihood/Total
Posterior

array([0.69230769, 0.23076923, 0.07692308])

In [7]:
Prior = np.array([0.4,0.3,0.2,0.1])
lambda_ = np.array([1,2,3,4])

In [8]:
hatp = np.sum(Prior*lambda_)
hatp

2.0

In [9]:
Poisson = lambda l,x: l**x*np.exp(-l)/np.math.factorial(x)

In [10]:
Likelihood = Poisson(lambda_,4)
Likelihood

<ipython-input-9-dfad4be094fa>:1: DeprecationWarning: `np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`
  Poisson = lambda l,x: l**x*np.exp(-l)/np.math.factorial(x)


array([0.01532831, 0.09022352, 0.16803136, 0.19536681])

In [11]:
Probx = np.sum(Prior*Likelihood)
Probx

0.0863413332964712

In [12]:
Posterior = (Likelihood*Prior)/Probx
Posterior

array([0.07101262, 0.31348898, 0.38922576, 0.22627264])

In [13]:
np.sum(Posterior)

1.0

In [15]:
np.sum(Posterior*lambda_)

2.7707584253176796