<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionalesI/blob/main/Semana8/GaussJordan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
A = np.array([[3.,-1.,-1.],[-1.,3.,1.],[2.,1.,4.]])
A

array([[ 3., -1., -1.],
       [-1.,  3.,  1.],
       [ 2.,  1.,  4.]])

In [9]:
b = np.array([1.,3.,7.])
b

array([1., 3., 7.])

In [13]:
np.linalg.solve(A,b)

array([1., 1., 1.])

In [10]:
def TriangularSuperior(A_, ones = False):

  A = A_.copy()
  n = A.shape[0]

  for i in range(n):

    for j in range(i+1,n):

      a = A[j,i]/A[i,i]
      A[j,:] -= a*A[i,:]

  return A

In [11]:
TriangularSuperior(A)

array([[ 3.        , -1.        , -1.        ],
       [ 0.        ,  2.66666667,  0.66666667],
       [ 0.        ,  0.        ,  4.25      ]])

In [12]:
np.linalg.det(A)

34.00000000000001

In [15]:
def GaussJordan(A_, b_):

  A = A_.copy()
  b = b_.copy()

  n = A.shape[0]

  for i in range(n):
    for j in range(i+1,n):
      a = A[j,i]/A[i,i]
      A[j,:] -= a*A[i,:]
      b[j] -= a*b[i]

  x = np.zeros_like(b)

  for i in reversed(range(n)):
    x[i] = b[i]

    for j in range(i+1,n):
      x[i] -= A[i,j]*x[j]

    x[i] /= A[i,i]


  return x

In [17]:
GaussJordan(A,b)

array([1., 1., 1.])