<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionalesI/blob/main/Semana7/MetodoJacobi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[3,-1,-1],[-1,3,1],[2,1,4]])
#A = np.array([[3,-1,-1],[3,-1,-1],[2,1,4]])

A

array([[ 3, -1, -1],
       [-1,  3,  1],
       [ 2,  1,  4]])

In [3]:
b = np.array([1.,3.,7.])
b

array([1., 3., 7.])

In [4]:
np.linalg.solve(A,b)

array([1., 1., 1.])

In [16]:
def Jacobi1(A,b,x0, itmax = 100, tolerancia = 1e-9):

  x = x0.copy()

  for it in range(itmax):

    xn = np.zeros_like(x)

    for i in range(A.shape[0]):

      sum_ = 0.

      for j in range(A.shape[1]):

        if i != j:
          sum_ += A[i,j]*x[j]

          xn[i] = (b[i] - sum_)/A[i,i]

    if np.linalg.norm( np.dot(A,x)-b) < tolerancia:
      break

   # print(xn)

    x = xn.copy()
  print(it)
  return x, it

In [17]:
from typing import Iterator
x0 = np.array([0.,0.,0.])
x,_ = Jacobi1(A,b,x0)

21


In [18]:
def Jacobi2(A,b,x0, itmax = 100, tolerancia = 1e-9):

  x = x0.copy()
  u = x.copy()
  sumk = x.copy()

  residuo = np.linalg.norm( np.dot(A,x) - b )

  it = 0
  var = 0.
  sum_ = 0.

  while residuo > tolerancia and it < itmax:

    u[:] = 0.
    #sumk[:] = 0. + var


    for i in range(A.shape[0]):
      sum_ = 0. + var

      #sum_ = 0.

      for j in range(A.shape[1]):

        if i != j:
          sum_ += A[i,j]*x[j]

        u[i] = (b[i] - sum_)/A[i,i]

      var = sum_

    x = u.copy()
    residuo = np.linalg.norm( np.dot(A,x) - b )

    it += 1

  print(it)
  return x, it

In [19]:
def GaussSeidel(A, b, x0, itmax=100, tolerancia=1e-9):
    x = x0.copy()
    residuo = np.linalg.norm(np.dot(A, x) - b)
    it = 0

    while residuo > tolerancia and it < itmax:
        for i in range(A.shape[0]):
            sum_ = 0.
            for j in range(A.shape[1]):
                if i != j:
                    sum_ += A[i, j] * x[j]
            x[i] = (b[i] - sum_) / A[i, i]

        residuo = np.linalg.norm(np.dot(A, x) - b)
        it += 1

    print(it)
    return x, it

In [20]:
x0 = np.array([0.,0.,0.])
x,_ = GaussSeidel(A,b,x0)

17


In [9]:
x

array([-3.36686390e-06,  2.85706389e-01,  1.14286159e+00])