<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionalesI/blob/main/Semana7/MetodoJacobi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

In [15]:
A = np.array([[3,-1,-1],[-1,3,1],[2,1,4]])
A

array([[ 3, -1, -1],
       [-1,  3,  1],
       [ 2,  1,  4]])

In [16]:
b = np.array([1.,3.,7.])
b

array([1., 3., 7.])

In [17]:
np.linalg.solve(A,b)

array([1., 1., 1.])

In [27]:
def Jacobi(A,b,x0, itmax = 1000, tolerancia = 1e-16):

  x = x0.copy()

  for it in range(itmax):

    # Hacemos una copia del vector x
    x_new = np.copy(x)

    for i in range(A.shape[0]):

      # Contabilizamos la suma del iterador
      Suma = 0.
      for j in range(A.shape[1]):
        if i != j:
          Suma += A[i,j]*x[j]
          # La diferencia radica en usar todo el vector no actualizado x
          x_new[i] = (b[i] - Suma)/A[i,i]

    #print(x_new)

    # Criterio de convergencia
    if np.linalg.norm( np.dot(A,x_new)-b) < tolerancia:
      break

    x = np.copy(x_new)

  print(it)

  return x, it

In [28]:
x0 = np.array([0.,0.,0.])
x,_ = Jacobi(A,b,x0)
x

34


array([1., 1., 1.])

In [31]:
def GaussSeidel(A,b,x0, itmax = 100, tolerancia = 1e-16):

  x = x0.copy()

  for it in range(itmax):

    # Hacemos una copia del vector x
    x_new = np.copy(x)

    for i in range(A.shape[0]):

      # Contabilizamos la suma del iterador
      Suma = 0.
      for j in range(A.shape[1]):
        if i != j:
          Suma += A[i,j]*x_new[j]
          # La diferencia radica en que ahora la suma es
          # calcula usando x_new recien actualizado
          x_new[i] = (b[i] - Suma)/A[i,i]

    #print(x_new)

    # Criterio de convergencia
    if np.linalg.norm( np.dot(A,x_new)-b) < tolerancia:
      break

    x = np.copy(x_new)

  print(it)

  return x, it

In [32]:
x0 = np.array([0.,0.,0.])
x,_ = GaussSeidel(A,b,x0)
print(x)

25
[1. 1. 1.]
