<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionalesI/blob/main/Semana7/MetodoJacobi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np

In [57]:
A = np.array([[3,-1,-1],[-1,3,1],[2,1,4]])
#A = np.array([[3,-1,-1],[3,-1,-1],[2,1,4]])

A

array([[ 3, -1, -1],
       [-1,  3,  1],
       [ 2,  1,  4]])

In [58]:
b = np.array([1.,3.,7.])
b

array([1., 3., 7.])

In [59]:
np.linalg.solve(A,b)

array([1., 1., 1.])

In [60]:
def Jacobi1(A,b,x0, itmax = 20, tolerancia = 1e-7):

  x = x0.copy()

  for it in range(itmax):

    xn = np.zeros_like(x)

    for i in range(A.shape[0]):

      sum_ = 0.

      for j in range(A.shape[1]):

        if i != j:
          sum_ += A[i,j]*x[j]

          xn[i] = (b[i] - sum_)/A[i,i]

    if np.linalg.norm(xn - x) < tolerancia:
      break

   # print(xn)

    x = xn.copy()

  return x, it

In [66]:
from typing import Iterator
x0 = np.array([1.,1.,1.])
x,_ = Jacobi1(A,b,x0)

In [67]:
x

array([1., 1., 1.])

In [63]:
x

array([1., 1., 1.])

In [64]:
np.dot(A,x)

array([1., 3., 7.])

In [65]:
b

array([1., 3., 7.])