<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionalesI/blob/main/Semana14/Markov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
T = np.array([[0.30,0.30,0.30,0.10],\
              [0.25,0.25,0.50,0.00],\
              [0.15,0.55,0.10,0.20],\
              [0.10,0.20,0.30,0.40]])

In [3]:
np.sum(T,axis=1)

array([1., 1., 1., 1.])

In [5]:
np.dot(np.dot(T,T),T)

array([[0.2115  , 0.3445  , 0.31    , 0.134   ],
       [0.216875, 0.329375, 0.3325  , 0.12125 ],
       [0.204625, 0.372125, 0.2775  , 0.14575 ],
       [0.19575 , 0.33075 , 0.309   , 0.1645  ]])

In [6]:
np.linalg.matrix_power(T,20)

array([[0.20908005, 0.34587814, 0.30764636, 0.13739546],
       [0.20908005, 0.34587814, 0.30764635, 0.13739546],
       [0.20908005, 0.34587813, 0.30764636, 0.13739546],
       [0.20908005, 0.34587814, 0.30764636, 0.13739546]])

In [9]:
Initial = np.array([1,0,0,0])
States = np.array([Initial])

for i in range(10):
    Initial = np.dot(Initial,T)
    States = np.vstack((States,Initial))

States

array([[1.        , 0.        , 0.        , 0.        ],
       [0.3       , 0.3       , 0.3       , 0.1       ],
       [0.22      , 0.35      , 0.3       , 0.13      ],
       [0.2115    , 0.3445    , 0.31      , 0.134     ],
       [0.209475  , 0.346875  , 0.3069    , 0.13675   ],
       [0.20927125, 0.34570625, 0.307995  , 0.1370275 ],
       [0.20910994, 0.34601069, 0.30754225, 0.13733713],
       [0.2091007 , 0.34585132, 0.30769369, 0.13735429],
       [0.20908252, 0.34589543, 0.30763153, 0.13739053],
       [0.20908239, 0.34587406, 0.30765278, 0.13739077],
       [0.20908023, 0.34588042, 0.30764426, 0.1373951 ]])

In [ ]:
# Cada estado es un caracter en el generador de lenguaje
Dict = {0:'a',1:'o',2:'m',3:'r',4:' '}

In [ ]:
Dict[0]

'a'

In [ ]:
# Ya esta traspuesta
T = np.array([[0.10,0.10,0.80,0.10,0.00],\
              [0.10,0.10,0.00,0.70,0.00],\
              [0.00,0.70,0.10,0.10,0.00],\
              [0.00,0.10,0.10,0.10,0.90],\
              [0.80,0.00,0.00,0.00,0.10],\
             ])
T

array([[0.1, 0.1, 0.8, 0.1, 0. ],
       [0.1, 0.1, 0. , 0.7, 0. ],
       [0. , 0.7, 0.1, 0.1, 0. ],
       [0. , 0.1, 0.1, 0.1, 0.9],
       [0.8, 0. , 0. , 0. , 0.1]])