<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionalesI/blob/main/Semana14/Markov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
T = np.array([[0.30,0.30,0.30,0.10],\
              [0.25,0.25,0.50,0.00],\
              [0.15,0.55,0.10,0.20],\
              [0.10,0.20,0.30,0.40]])

In [3]:
np.sum(T,axis=1)

array([1., 1., 1., 1.])

In [5]:
np.dot(np.dot(T,T),T)

array([[0.2115  , 0.3445  , 0.31    , 0.134   ],
       [0.216875, 0.329375, 0.3325  , 0.12125 ],
       [0.204625, 0.372125, 0.2775  , 0.14575 ],
       [0.19575 , 0.33075 , 0.309   , 0.1645  ]])

In [6]:
np.linalg.matrix_power(T,20)

array([[0.20908005, 0.34587814, 0.30764636, 0.13739546],
       [0.20908005, 0.34587814, 0.30764635, 0.13739546],
       [0.20908005, 0.34587813, 0.30764636, 0.13739546],
       [0.20908005, 0.34587814, 0.30764636, 0.13739546]])

In [9]:
Initial = np.array([1,0,0,0])
States = np.array([Initial])

for i in range(10):
    Initial = np.dot(Initial,T)
    States = np.vstack((States,Initial))

States

array([[1.        , 0.        , 0.        , 0.        ],
       [0.3       , 0.3       , 0.3       , 0.1       ],
       [0.22      , 0.35      , 0.3       , 0.13      ],
       [0.2115    , 0.3445    , 0.31      , 0.134     ],
       [0.209475  , 0.346875  , 0.3069    , 0.13675   ],
       [0.20927125, 0.34570625, 0.307995  , 0.1370275 ],
       [0.20910994, 0.34601069, 0.30754225, 0.13733713],
       [0.2091007 , 0.34585132, 0.30769369, 0.13735429],
       [0.20908252, 0.34589543, 0.30763153, 0.13739053],
       [0.20908239, 0.34587406, 0.30765278, 0.13739077],
       [0.20908023, 0.34588042, 0.30764426, 0.1373951 ]])

In [10]:
# Cada estado es un caracter en el generador de lenguaje
Dict = {0:'a',1:'o',2:'m',3:'r',4:' '}

In [11]:
Dict[0]

'a'

In [12]:
# Ya esta traspuesta
T = np.array([[0.10,0.10,0.80,0.10,0.00],\
              [0.10,0.10,0.00,0.70,0.00],\
              [0.00,0.70,0.10,0.10,0.00],\
              [0.00,0.10,0.10,0.10,0.90],\
              [0.80,0.00,0.00,0.00,0.10],\
             ])
T

array([[0.1, 0.1, 0.8, 0.1, 0. ],
       [0.1, 0.1, 0. , 0.7, 0. ],
       [0. , 0.7, 0.1, 0.1, 0. ],
       [0. , 0.1, 0.1, 0.1, 0.9],
       [0.8, 0. , 0. , 0. , 0.1]])

In [27]:
def GetString(Initial,T,N=int(10)):

  tex = ''
  States = np.array([Initial])
  for i in range(N):
    Initial = np.dot(T,Initial)
    States = np.vstack((States,Initial))

    print(Initial)
    index = np.where(np.amax(Initial)==Initial)[0]

    tex = tex + Dict[index[0]]

  return tex

In [29]:
Initial = np.array([0,0,1,0,0])
GetString(Initial,T,50)

[0.8 0.  0.1 0.1 0. ]
[0.17 0.15 0.02 0.02 0.64]
[0.05  0.046 0.109 0.595 0.2  ]
[0.1563 0.4261 0.1026 0.255  0.06  ]
[0.16582 0.23674 0.33403 0.13237 0.13104]
[0.320717 0.132915 0.212358 0.18825  0.14576 ]
[0.2340746 0.1771382 0.1331013 0.1845363 0.2711496]
[0.16605595 0.17029669 0.1557605  0.29351222 0.21437464]
[0.18759489 0.23909382 0.16413496 0.25489412 0.15428222]
[0.19946625 0.22109475 0.20926858 0.20466629 0.16550413]
[0.22993759 0.1853225  0.19615981 0.21245668 0.17612341]
[0.21969953 0.19024569 0.1705874  0.21790497 0.20156242]
[0.19925494 0.193528   0.17202122 0.23927998 0.19591586]
[0.20082327 0.20677428 0.17659972 0.2368072  0.17899554]
[0.20572025 0.20652479 0.18608269 0.2231141  0.17855817]
[0.21240206 0.19740438 0.18548703 0.22227451 0.18243202]
[0.21159772 0.1965728  0.17895922 0.22470541 0.18816485]
[0.20645497 0.19811084 0.17796742 0.22937211 0.18809466]
[0.20576773 0.20101706 0.17941154 0.22983023 0.18397344]
[0.20719073 0.20155964 0.18163612 0.22660198 0.18301153]


'a roma rroaarrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'