<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionalesI/blob/main/Semana2/Soporte2D_POO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

In [8]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [9]:
A.shape

(2, 2)

In [10]:
A[:,0]

array([1, 3])

In [11]:
A[:,-1]

array([2, 4])

In [12]:
A[1,1]

4

In [13]:
A[1][1]

4

In [ ]:
# Queremos pintar