<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionalesI/blob/main/Semana5/CuadraturaGauss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym

In [2]:
a = 0
b = 0.25*np.pi
f = lambda x: np.sin(x)

In [3]:
Roots, Weights = np.polynomial.legendre.leggauss(4)
t = 0.5*( (b-a)*Roots + b + a )
Integral = 0.5*(b-a)*np.sum(Weights*f(t))
Roots

array([-0.86113631, -0.33998104,  0.33998104,  0.86113631])

In [4]:
Weights

array([0.34785485, 0.65214515, 0.65214515, 0.34785485])

In [5]:
print('{:.70f}'.format(Integral))
print('{:.70f}'.format(1-np.cos(0.25*np.pi)))

0.2928932187890722627088280205498449504375457763671875000000000000000000
0.2928932188134524272626890706305857747793197631835937500000000000000000


In [6]:
def GetNewtonMethod(f,df,xn,itmax = 10000, precision=1e-14):

    error = 1.
    it = 0

    while error >= precision and it < itmax:

        try:

            xn1 = xn - f(xn)/df(xn)

            error = np.abs( (xn1-xn)/xn )
           # error = np.abs(f(xn)/df(xn))

        except ZeroDivisionError:
            print("zero division")

        xn  = xn1
        it += 1

    #print('Raiz:',xn,it)

    if it == itmax:
        return False
    else:
        return xn

In [7]:
def GetAllRoots(f,df,x, tolerancia=13):

    Roots = np.array([])

    for i in x:

        root = GetNewtonMethod(f,df,i)

        if root != False:

            croot = np.round( root, tolerancia )

            if croot not in Roots:
                Roots = np.append( Roots, croot )

    # Ordenamos las raices
    Roots.sort()

    return Roots

In [8]:
def GetLegendre(n):

  x = sym.Symbol('x',Real=True)
  y = sym.Symbol('y',Real=True)

  y = (x**2 - 1)**n

  p = sym.diff(y,x,n)/(2**n * np.math.factorial(n))

  return p

In [9]:
Legendre = []
DLegendre = []

x = sym.Symbol('x',Real=True)
n=4

for i in range(n+1):

    poly = GetLegendre(i)

    Legendre.append(poly)
    DLegendre.append(sym.diff(poly,x))

<ipython-input-8-adbe1921b909>:8: DeprecationWarning: `np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`
  p = sym.diff(y,x,n)/(2**n * np.math.factorial(n))


In [10]:
def GetRootsPolynomial(n,xi,poly,dpoly):

    x = sym.Symbol('x',Real=True)
    pn = sym.lambdify([x],poly[n],'numpy')
    dpn = sym.lambdify([x],dpoly[n],'numpy')
    Roots = GetAllRoots(pn,dpn,xi)

    return Roots

In [11]:
xi = np.linspace(-1,1,100,dtype=np.longdouble)
Roots = GetRootsPolynomial(4,xi,Legendre,DLegendre)

In [12]:
Roots

array([-0.86113631, -0.33998104,  0.33998104,  0.86113631], dtype=float128)

In [13]:
Legendre[0]

1

In [14]:
def GetWeights(Roots,Dpoly):

  Weights = np.array([])

  x = sym.Symbol('x',real=True)
  dpn = sym.lambdify([x],Dpoly[n],'numpy')

  for r in Roots:
    Weights = np.append(Weights,2/((1-r**2)*dpn(r)**2))

  return Weights


In [15]:
Weights1 = GetWeights(Roots,DLegendre)

In [16]:
Weights1

array([0.34785485, 0.65214515, 0.65214515, 0.34785485], dtype=float128)

In [17]:
Weights

array([0.34785485, 0.65214515, 0.65214515, 0.34785485])